name = "lloromc"
author = "chech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69e66ae9d82048beff0054466a3df8124986e072b1278e9fe35075fa0b7f7c2f"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
