name = "lloromc"
author = "chech"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e73426431e4217eee67044ac9510ee85ee4e3c0cef3cd62bf5b1e87b53eb227"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"
